export const CACHE_TAGS = {
  GRANTS: "grants",
  GRANT_BY_ID: "grant-by-id",
  LEADERBOARDS: "leaderboards",
  LEADERBOARD_BY_ID: "leaderboard-by-id",
  SPONSORS: "sponsors",
  SPONSOR_BY_SLUG: "sponsor-by-slug",
  TALENT_PROFILE: "talent-profile",
  TALENT_SOCIALS: "talent-socials",
  TALENT_BUILDER_SCORE: "talent-builder-score",
  TALENT_ACCOUNTS: "talent-accounts",
  TALENT_CREDENTIALS: "talent-credentials",
  TALENT_DATA_ISSUERS_CREDENTIALS: "talent-data-issuers-credentials",
  TALENT_CREDENTIALS_DATAPOINTS: "talent-credentials-datapoints",
  SEARCH: "search",
  STATS_DAILY: "stats-daily",
  TALENT_LOOKUP: "talent-lookup",
  CHART_METRICS: "chart-metrics",
  SEARCH_ADVANCED: "search-advanced",
  SEARCH_FIELDS: "search-fields",
  SEARCH_DOCUMENTS: "search-documents",
  NOTIFICATION_TOKENS: "notification-tokens",
  ANALYTICS_ACTIVE_USERS: "analytics-active-users",
  ANALYTICS_CSV_DATA: "analytics-csv-data",
};

export const CACHE_60_MINUTES = 60 * 60;
